name: podium
description: A New Standard of Living.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.6

dependencies:
  authentication_repo:
    path: lib/packages/authentication_repo
  bloc: ^8.1.0
  cloud_firestore: ^4.2.0
  equatable: ^2.0.3
  firebase_analytics: ^10.1.1
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.7
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_facebook_auth: ^5.0.6
  flutter_launcher_icons: ^0.11.0
  flutter_pdfview: ^1.2.5
  flutter_signin_button: ^2.0.0
  flutter_stripe: ^7.0.0
  font_awesome_flutter: ^9.0.0
  form_builder_image_picker: ^3.1.0
  form_builder_validators: ^8.4.0
  form_inputs:
    path: lib/packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.6
  meta: ^1.7.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/src/assets/images/

  fonts:
    - family: Questrial
      fonts:
        - asset: lib/src/assets/fonts/Questrial-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: lib/src/assets/images/podium_logo.png
