name: podium

on: [pull_request, push]

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.8
  setup-dart:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.5.0
        with:
          sdk: '3.0.0'