name: podium

on: [pull_request, push]

jobs:

  setup-dart:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.5.0
     
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    
    